starting-balance: 1000
#multiplier > 1
starting-multiplier: 1
online-mode: false
MySQL:
  enabled: false
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "password"
  table: "coinTable"
  database: "fconomy"
Sounds:
  correct: "LEVEL_UP;10;1"
  player_success_send: "LEVEL_UP;10;4.5"
  player_receive_send: "NOTE_PLING;10;1"
  error: "VILLAGER_NO;10;1"
Messages:
  plugin_prefix: "&a[Coins] "
  reload: '&aFconomy recargado!'
  target_not_online: "&cEl jugador %player% no se encuentra en linea"
  number_is_0: "&cDebes escribir un numero mayor a 0."
  add_coins: "&aSe han agregado &e%coins% &acoins a &e%player%"
  add_coin_title: "&a+%coin% Coin"
  add_coins_title: "&a+%coins% Coins"
  add_coins_help: "&cUso Correcto &e/coins add <player> <coins>"
  invalid_number: "&cDebes escribir un numero valido."
  set_coins: "&aSe ha seteado &e%coins% &acoins a &e%player%"
  set_coins_help: "&cUso Correcto &e/coins set <player> <coins>"
  remove_coins: "&aSe ha removido &e%coins% &acoins a &e%player%"
  remove_coins_help: "&cUso Correcto &e/coins remove <player> <coins>"
  send_coins_to_yourself: "&cNo puedes enviarte dinero a ti mismo!"
  player_send_coins_success: "&aSe ha enviado &e%coins% &acoins a &e%player%"
  player_receive_coins_succes: "&e%player% &ate ha enviado &e%coins% &acoins"
  send_coins_help: "&cUso Correcto &e/coins send <player> <coins>"
  not_enough_coins: "&cNo tienes coins suficientes"
  player_coins: "&eEl jugador %player% tiene &a%coins% &ecoins"
  own_coins: "&eTienes &a%coins% &ecoins"
  set_multiplier: "&aEl multiplicador del jugador &e%player% se ha seteado a x%multiplier%"
  set_multiplier_help: "&cUso Correcto &e/multiplier set <player> <multiplier>"
  player_multiplier: "&eEl jugador %player% tiene un multiplicador de &ax%multiplier%"
  no_perm: "&cNo tienes permiso para ejecutar este comando"
  help:
    - "&e/ecoins - muestra tus coins"
    - "&e/ecoins <player> - muestra los coins de un jugador"
    - "&e/ecoins send <player> <coins> - envia coins a un jugador"
#fconomy.see - /coins {player}
#fconomy.admin - all permissions
#fconomy.* - all permissions
#fconomy.send - /coins send {player} {coins}
#fconomy.remove - /coins remove {player} {coins}
#fconomy.set - /coins set {player} {coins}
#fconomy.add - /coins add {player} {coins}
#fconomy.reload - /coins reload