name: FConomy
author: FrancoBM
description: Economy for this server
version: 1.4.2
api-version: 1.13
main: com.francobm.fconomy.Main
softdepend: [MVdWPlaceholderAPI, PlaceholderAPI, ShopGUIPlus, SkyWars, Vault]
commands:
  coins:
    description: get your coins
    usage: /<command>
    aliases: [money, balance]
  multiplier:
    description: multiplier for coins
    usage: /<command>